id: I34D498D7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T19:14:22+00:00'
last_modified: '2022-06-08T12:32:37.815209+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016752
  title: ཐུགས་རྗེ་ཆེན་པོ་རྩ་གསུམ་སྙིང་ཐིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2413':
      image_group_id: I01JW68
      title: ''
      total_pages: 390
      order: 1
      base_file: 2413.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
