id: P009646
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016752
  title: ཐུགས་རྗེ་ཆེན་པོ་རྩ་གསུམ་སྙིང་ཐིག
  author: ''
  volumes:
    3892fe288afe4d9a9ad668e2584db877:
      image_group_id: I01JW68
      title: ''
      volume_number: 1
      total_pages: 390
      base_file: v001.txt
